### ISSUE TITLE
PEAC shiny script

### ISSUE THREAD

**Issue by Shicheng-Guo** [myles-lewis/easylabel#22]
Dear Lewis, 

I am wondering whether the shiny frame of [peac.hpc.qmul.ac.uk/](https://peac.hpc.qmul.ac.uk/) is available on GitHub or not? 

Thanks. 

Shicheng

**Comment by myles-lewis** [comment]
Hi Shicheng,
No I'm sorry, it's not available.
Best wishes,
Myles
