### ISSUE TITLE
visualization dashboard: https://r4ra.hpc.qmul.ac.uk/

### ISSUE THREAD

**Issue by Shicheng-Guo** [myles-lewis/easylabel#23]
Dear Myles, 

Thank you for the great contribution to r4ra project. I am wondering is there any public code information about the r4ra visualization dashboard? 

https://r4ra.hpc.qmul.ac.uk/

Thanks. 

Shicheng

**Comment by myles-lewis** [comment]
Hi Shicheng,
No that code is not public as it was very much bespoke to that project and not written to be generalized. We have published an R package which has been designed to generalize the generation of a shiny website. See here:
https://cran.r-project.org/web/packages/shinyExprPortal/index.html

Bw, Myles
